config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/cafe", to: "cafe#about"

  # CRUD routes for MenuItem
  root to: "cafe#index"

  resources :cafe, as: :menu_items
  # post "/cafe", to: "cafe#create"
  # get "/cafe/:item_name", to: "cafe#show", as: "show_item"
  # patch "/cafe/:item_name", to: "cafe#update"
  # put "/cafe/:item_name", to: "cafe#update"
  # delete "/cafe/:item_name", to: "cafe#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cafe_controller.rb
class CafeController < ApplicationController
  # IMPORTANT!! REMOVE FOR PRODUCTION!
  skip_before_action :verify_authenticity_token
  before_action :set_item, only: [:show, :update, :destroy, :edit]

  def index
    @currency_symbol = "$"
    @menu = MenuItem.order(:name)
  end

  def new
    @item = MenuItem.new
  end

  def edit    
  end

  def about
    render json: MenuItem.all
  end

  def create
    @item = MenuItem.create(item_params)
    redirect_to @item
  end

  def update
    @item.update(item_params)
    redirect_to @item
  end

  def show
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def set_item
    @item = MenuItem.find(params[:id])
  end

  def item_params
    params.require(:menu_item).permit(:name, :price, :qty)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/views/cafe/_form.html.erb
<%= form_with model: @item do |f| %>
    <%= f.text_field :name, placeholder: "Item Name" %>
    <%= f.number_field :price, step: "0.01", placeholder: "Item Price" %>
    <%= f.number_field :qty, placeholder: "Qty On Hand" %>

    <%= f.submit %>
<% end %>

app/views/cafe/edit.html.erb
<h1>Edit Menu Item</h1>

<%= render 'form' %>

app/views/cafe/index.html.erb
<h1>Welcome to Coder Cafe!</h1>

<p><%= link_to "New Menu Item", new_menu_item_path %></p>

<table>
    <tr>
        <th>Item</th>
        <th>Price</th>
        <th>Actions</th>
    </tr>
    <% @menu.each do |item| %>
        <tr>
            <td><%= link_to item.name.capitalize, item %></td>
            <td><%= "#{@currency_symbol}%.2f" % item.price %></td>
            <td>
                <%= link_to "Edit", edit_menu_item_path(item) %>
                |
                <%= link_to "Delete", item, method: :delete, data: { confirm: "Are you sure?" } %>
            </td>
        </tr>
    <% end %>
</table>

app/views/cafe/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form' %>

app/views/cafe/show.html.erb
<h1>Menu Item</h1>

<table>
    <tr>
        <td>Name</td>
        <td><%= @item.name %></td>
    </tr>
    <tr>
        <td>Price</td>
        <td><%= @item.price %></td>
    </tr>
</table>
<p>
    <%= link_to "<< Back to Menu", root_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>